package org.gsarno.spring.db;

import java.util.List;

import org.gsarno.spring.db.dao.IDao;
import org.gsarno.spring.db.dao.Person;
import org.gsarno.spring.db.dao.PersonRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

public class DbAccess implements IDao {
    
    private JdbcTemplate jdbcTemplate;

    public void setJdbcTemplate(JdbcTemplate template) {
    this.jdbcTemplate = template;
    }

   
    public void create() {
        jdbcTemplate.update("CREATE TABLE Person(ID int generated by default as identity (start with 1) not null, FIRSTNAME VARCHAR(20) NOT NULL, LASTNAME VARCHAR(20) NOT NULL, PRIMARY KEY (ID))"); 
       }
    public void drop() {
        try
        {
          jdbcTemplate.update("DROP TABLE Person");
        }
        catch(Exception e)
        {
            
        }
       }
    public void insert(String firstName, String lastName) {

       // jdbcTemplate.update("CREATE TABLE Person(ID int generated by default as identity (start with 1) not null, FIRSTNAME VARCHAR(20) NOT NULL, LASTNAME VARCHAR(20) NOT NULL, PRIMARY KEY (ID))"); 
        jdbcTemplate.update("INSERT INTO PERSON (FIRSTNAME, LASTNAME) VALUES(?,?)",
            new Object[] { firstName, lastName });
      }

      public List<Person> select(String firstname, String lastname) {
        return jdbcTemplate
            .query("select  FIRSTNAME, LASTNAME from PERSON where FIRSTNAME = ? AND LASTNAME= ?",
                new Object[] { firstname, lastname },
                new PersonRowMapper());
      }

      public List<Person> selectAll() {
        return jdbcTemplate.query("select FIRSTNAME, LASTNAME from PERSON",
            new PersonRowMapper());
      }

      public void deleteAll() {
          jdbcTemplate.update("DELETE from PERSON");
      }

      public void delete(String firstName, String lastName) {
          jdbcTemplate.update("DELETE from PERSON where FIRSTNAME= ? AND LASTNAME = ?",
            new Object[] { firstName, lastName });
      }

}

